version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Europe/London"

  - package-ecosystem: "terraform" 
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Europe/London"